import { Inter } from "next/font/google";
import "./globals.css";
import App from "./_app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <App>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </App>
  );
}
