post_list:
  path: /posts
  controller: App\Post\Infrastructure\Controller\PostController::list
  methods: [GET]

post_create:
  path: /posts
  controller: App\Post\Infrastructure\Controller\PostController::create
  methods: [POST]

post_view:
  path: /posts/{id}
  controller: App\Post\Infrastructure\Controller\PostController::view
  methods: [GET]
  requirements:
    id: '\d+'  # Ensure the ID is numeric